title: Hayden Zhu

description: Hayden's Personal Web
markdown: kramdown
include: ["_pages"]

# social links
email: haydenzhuxz@gmail.com
linkedin_username: haydenz
github_username: haydenz

theme: jekyll-theme-minimal

