title: Hayden Zhu

description: Hayden' Personal Web
markdown: kramdown

email: haydenzhuxz@gmail.com
linkedin_username: haydenz
github_username: haydenz

theme: jekyll-theme-dinky

show_downloads: false
