# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise", "default"

# Settings
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-titles-from-headings
  - jekyll-remote-theme

# Author
author:
  name: Hayden Zhu
  bio:
    Financial Engineering
  # avatar           : /assets/images/haydenz.jpg
  links:
    - label: "Hong Kong"
      icon: "fas fa-2x fa-fw fa-map-marker-alt"
      url: "https://www.google.com/search?client=safari&rls=en&q=hong+kong&ie=UTF-8&oe=UTF-8#"
    - label: "Email"
      icon: "fas fa-2x fa-fw fa-envelope"
      url: "haydenzhuxz [at] gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/haydenz/"
    - label: "GitHub"
      icon: "fab fa-2x fa-fw fa-github"
      url: "https://github.com/haydenz"

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/haydenz"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/haydenz/"

# Contents
include:
  - _pages

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
