title: Hayden Zhu
author:
  email: haydenzhuxz@gmail.com
description: Hayden' Personal Web
markdown: kramdown

minima:
  social_links:
    linkedin: haydenz
    github: haydenz

theme: jekyll-theme-minimal

